sonar:
  image: sonarqube:6.0
  ports:
    - "9092:9092"
    - "9000:9000"
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysqlDb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  links:
    - mysqlDb
mysqlDb:
  image: daocloud.io/library/mysql:5.6.23
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=sonar
    - MYSQL_DATABASE=sonar
    - MYSQL_USER=sonar
    - MYSQL_PASSWORD=sonar
